# 基础镜像
FROM  openjdk:17
# author
MAINTAINER hospital-oa-system

# 挂载目录
VOLUME /home/hospital
# 创建目录
RUN mkdir -p /home/hospital
# 指定路径
WORKDIR /home/hospital
# 复制jar文件到路径
COPY ./jar/hospital-gateway.jar /home/hospital/hospital-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","hospital-gateway.jar"]