# 基础镜像
FROM  openjdk:17
# author
MAINTAINER hospital-oa-system

# 挂载目录
VOLUME /home/hospital
# 创建目录
RUN mkdir -p /home/hospital
# 指定路径
WORKDIR /home/hospital
# 复制jar文件到路径
COPY ./jar/hospital-auth.jar /home/hospital/hospital-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","hospital-auth.jar"]