# 基础镜像
FROM  openjdk:17
# author
MAINTAINER hospital-oa-system

# 挂载目录
VOLUME /home/hospital
# 创建目录
RUN mkdir -p /home/hospital
# 指定路径
WORKDIR /home/hospital
# 复制jar文件到路径
COPY ./jar/hospital-modules-job.jar /home/hospital/hospital-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","hospital-modules-job.jar"]